### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by enkore** [gkuhn1/django-admin-templates-twitter-bootstrap#1]
Hi,

I would be very happy to use your templates in one of my projects, but I need to know which license this is...?

**Comment by gkuhn1** [comment]
Hi, This is a GPL licensed software.
We do not offer any kind of support or warranty.
We just ask for you to share with other the bugfixes or updates if you do.

**Comment by enkore** [comment]
Thanks a lot! :)

> Hi, This is a GPL licensed software.
> We do not offer any kind of support or warranty.
> We just ask for you to share with other the bugfixes or updates if you do.
