### ISSUE TITLE
Update to last bootstrap version

### ISSUE THREAD

**Issue by gkuhn1** [gkuhn1/django-admin-templates-twitter-bootstrap#3]
# Help items:

http://twitter.github.com/bootstrap/upgrading.html

**Comment by tocer** [comment]
+1

**Comment by gkuhn1** [comment]
Did by pamelafox-coursera

https://github.com/gkuhn1/django-admin-templates-twitter-bootstrap/commit/4dbffacb1c65fc83b7921131cbe0f2dc410c23ad
